### ISSUE TITLE
Model downloaded successfully, but unable to open it 2 days later

### ISSUE THREAD

**Issue by piotrwest** [rebane2001/matterport-dl#115]
Hi, I've rather strange issue where the model was downloaded successfully, I was able to browse it, move around, look around.

However, then, 2 days later, I tried to host locally and browse the copy again - I wasn't able to (follow the same steps with activating environment etc.). The dollhouse view is loaded, and I can rotate it, but then upon a double click on any place in home the loader gets stuck as on the screenshot and the view doesn't change to FPV.

This happened at the current latest version: https://github.com/rebane2001/matterport-dl/commit/7a5fc5a6303d92a4b7ba1a024433667150a39af1

Any ideas why this might happen? Both initially & later I did:

```
pyenv shell 3.12.4
source venv/bin/activate
python matterport-dl.py foo123 127.0.0.1 8088
```

Thanks for your help!

## Screenshot

![Screenshot 2024-08-05 at 23 14 52](https://github.com/user-attachments/assets/137982df-1ab6-4ae5-82b5-bde05c94b9f5)

**Comment by mitchcapper** [comment]
Thanks!   They changed the method they use for 'expired' content checking so needed new defeat for that.   Also found the proxy would not proxy background-images (which is ok as the downloader also wasn't able to download them any more:)).  Both those things are fixed.  Re-run matterport-dl.py on your existing download (do not need to delete I believe) and it should now work (after updating to master that is).

**Comment by piotrwest** [comment]
Thanks for quick answer! However, I'm afraid the issue still persists... After you pushed the fix, I've updated code, removed old downloads, triggered a new download, and unfortunately 2 days later I've the same issue as before - loader stuck. I agree however it must be something with the expiration, if I change my computer time 2 days back, it resolves the issue.

**Comment by mitchcapper** [comment]
OK so while I added a 3rd bypass check I had commented it out in a goal of making sure the fixing of the actual expiry dates was fixed.  I found the expiry dates missed so that should happen on all new downloads.  

To retest this without waiting 2 days open the file js/showcase.modified.js and replace the string `this.onStale` with `this.onStal` and it should make the model work right away.  Granted you could also adv time by two days but this should fix it.

**Comment by piotrwest** [comment]
With the replacement in the js file it worked, thanks a lot!
