### ISSUE TITLE
[Bug]: Getting 429 Request error

### ISSUE THREAD

**Issue by Mottomi** [rebane2001/matterport-dl#184]
### One or more sample matterport IDs / urls that reproduce the issue

https://discover.matterport.com/space/nyr5AcShdSX

### Can you reproduce this issue with the sample small digital twin https://my.matterport.com/show/?m=EGxFGTFyC9N

Yes

### Python version

3.13.1

### Steps to reproduce

Tried using matterport-dl.py to download a scene.

### What went wrong

Get a 429 Error:
`Traceback (most recent call last):
  File "I:\Lidar\matterport-dl-main\matterport-dl.py", line 299, in downloadFile
    response.raise_for_status()  # Raise an exception if the response has an error status code
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Utilities\Python\Lib\site-packages\curl_cffi\requests\models.py", line 141, in raise_for_status
    raise RequestsError(f"HTTP Error {self.status_code}: {self.reason}")
curl_cffi.requests.errors.RequestsError: HTTP Error 429:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "I:\Lidar\matterport-dl-main\matterport-dl.py", line 1841, in <module>
    main()
    ~~~~^^
  File "I:\Lidar\matterport-dl-main\matterport-dl.py", line 1835, in main
    asyncio.run(initiateDownload(pageId))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Utilities\Python\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "D:\Utilities\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\Utilities\Python\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "I:\Lidar\matterport-dl-main\matterport-dl.py", line 1246, in initiateDownload
    await downloadCapture(getPageId(url))
  File "I:\Lidar\matterport-dl-main\matterport-dl.py", line 962, in downloadCapture
    await downloadMainAssets(pageid, accessurl)
  File "I:\Lidar\matterport-dl-main\matterport-dl.py", line 784, in downloadMainAssets
    await downloadDAM(accessurl, modeldata["job"]["uuid"])
  File "I:\Lidar\matterport-dl-main\matterport-dl.py", line 175, in downloadDAM
    await downloadFile("UUID_DAM50K", True, accessurl.format(filename=f"{uuid}_50k.dam"), f"..{os.path.sep}{uuid}_50k.dam", key_type=AccessKeyType.FILES3_TEMPLATE_KEY)
  File "I:\Lidar\matterport-dl-main\matterport-dl.py", line 323, in downloadFile
    raise Exception(f"Request error for url: {url} ({type}) that would output to: {file} of: {err}") from err
Exception: Request error for url: https://cdn-2.matterport.com/models/49b3e3ce762e4407b5bf1ea31b8e0a30/assets/~/5446c14bbc9946c0b6d548e36b0dcc51_50k.dam?t=2-f56468f0c03159e51a2db97a9d186e03a8c7ed62-1751070755-0 (UUID_DAM50K) that would output to: ..\5446c14bbc9946c0b6d548e36b0dcc51_50k.dam of: HTTP Error 429:`

### Workarounds

_No response_

**Comment by VishalPokharel** [comment]
Hi @Mottomi ! I got the same problem with: ``python3 run.py EGxFGTFyC9N``
Do you have updates on this?

**Comment by Mottomi** [comment]
@VishalPokharel  I tried the changes you made; going all the way down to `MAX_CONCURRENT_REQUESTS = 1 MAX_CONCURRENT_TASKS = 1`.

But unfortunately I'm still getting the same 429 HTTP Error


```
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 42.57it/s]
Downloading matterport tags / embedded attachments...
0it [00:00, ?it/s]
Downloading primary model assets has 4k: True...
Traceback (most recent call last):
  File "I:\Lidar\matterport-dl-main\matterport-dl.py", line 299, in downloadFile
    response.raise_for_status()  # Raise an exception if the response has an error status code
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "I:\Lidar\matterport-dl-main\venv\Lib\site-packages\curl_cffi\requests\models.py", line 141, in raise_for_status
    raise RequestsError(f"HTTP Error {self.status_code}: {self.reason}")
curl_cffi.requests.errors.RequestsError: HTTP Error 429:
```

**Comment by mitchcapper** [comment]
I haven't had a chance to investigate yet but 429 is rate limiting.  Likely that rate is tied to an IP address.  Sounds like lowering the rate as specified above will work but if is possible some rate limits are not reset instantly if you exceed them.   Try waiting 24 hours then doing it at the lower rate or rotating your IP by rebooting your modem.  Using a local round robin proxy would likely also help but I am not going to spend time detailing that right now. Keep in mind matterport dl does resume downloads so if you have a very large model it may only be able to say download 1\3rd a day under the new rate limits.

**Comment by VishalPokharel** [comment]
@Mottomi @frosthielo 
Can you try by replacing the current matterport-dl.py with [this](https://www.notion.so/matterport-dl-2214b30c278980dfa7a0db0a0659f7f6?source=copy_link) version.
It takes a while to download, but worked fine for [EGxFGTFyC9N](https://my.matterport.com/show/?m=EGxFGTFyC9N)
``Generating tile_mesh crop images locally (no progress shown)...
Done, Total fetches: 2350 Skipped: 2 (0%) actual Request: 2348 (100%) Success: 2314 (98%) Failed403: 6 (0%) Failed404: 1 (0%) FailedUnknown: 27 (1%) GeneratedCrops: None!
(base) vishalpokharel@Vishals-MacBook-Pro matterport-dl-main % ``

TODO:
1) Optimize to improve speed/performance.
2) Test with other tours to confirm broader compatibility.

**Comment by Mottomi** [comment]
Just an update that I've reverted to the current version of matterport-dl.py and tried downloading a scene after waiting for 2 days. Still getting the 429 error.

**Comment by frosthielo** [comment]
@VishalPokharel - the version of matterport-dl.py that you had linked in your comment below seems to have worked:
> Can you try by replacing the current matterport-dl.py with [this](https://www.notion.so/matterport-dl-2214b30c278980dfa7a0db0a0659f7f6?source=copy_link) version.

I write seems because when I tried it again even after using a different IP as @mitchcapper suggested with 
>Try waiting 24 hours then doing it at the lower rate or rotating your IP by rebooting your modem

it still didn't work, and gave the same HTTP Error 429 right after `Downloading primary model assets has 4k: True...` as it had done initially, despite the lower rate and the breaking up of downloaded files into smaller batches.

But I tried again using a different connection type (phone hotspot vs wifi) to see if it would make a difference, and while all the batches downloaded much slower (I assume due to a more limited connection speed), it actually worked and ran successfully without any errors. It took maybe 16 hours to run at that speed, but everything is fine now and I can host my matterport tour no problem.

I don't know enough to attribute this success to the new script, the slow download speeds, new IP address, or a combination of/all of them, but thanks to everyone in this thread for helping me out and getting it to work :)

**Comment by VishalPokharel** [comment]
@mitchcapper  I realize I didn’t structure my explanation clearly earlier. What I actually did was route each request through the ScraperAPI instead of using my local IP to avoid 429 error, code is same as matterport-dl.py, with minor changes.

**Comment by mitchcapper** [comment]
> I realize I didn’t structure my explanation clearly earlier. I simply routed my each request through ScraperAPI

That makes sense.   The idea being to use a set of proxies to distribute the requests over several ips was my thought on a local proxy.    The browser can request good bit of the model pretty rapidly though so we should be able to figure out a pretty good balance but may need to randomize our requests.

**Comment by Mottomi** [comment]
Just wanted to give a last update that I was able to download some scenes at full speed today. Maybe its a 3+ week period before they reset the rate limit on my IP.
